version: '2'
services:
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        volumes_from:
            - php
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./var/logs/nginx:/var/log/nginx
        depends_on:
            - php
    php:
        build:
            context: ./docker/php/
        volumes:
            - ./:/var/www/code
        expose:
            - 9000
    mysql_cinema:
        image: mysql:5.6
        ports:
            - 3333:3306
        volumes:
            - ./var/data/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 8888:80
        depends_on:
            - mysql_cinema
        environment:
            PMA_HOST: mysql_cinema
